import { readFileSync } from "node:fs";
import { registryReport } from "../../scripts/registry-report";

// docs/evidence.md's registry listing is the single place non-documented behavior is listed
// (docs/evidence.md "Documented, inferred, chosen"). It is generated by
// scripts/registry-report.ts, not hand-maintained; this test runs the report and asserts the
// fenced block still equals its output, so the listing cannot drift from registry/evidence.json.
test("docs/evidence.md's registry block matches the generated report", () => {
  // Imported in-process: spawning `npx tsx` from a Vitest worker deadlocked the parallel run.
  // The report opens with a newline; the fenced block starts at "## documented".
  const report = registryReport().replace(/^\n/, "");
  const doc = readFileSync("docs/evidence.md", "utf8");
  const match = doc.match(/```\n(## documented\n[\s\S]*?)```/);
  expect(match, "docs/evidence.md is missing its fenced registry block").not.toBeNull();
  expect(match![1]).toBe(report);
});
