//// GENERATED by scripts/gen-vocab.mjs from registry/vocab/*.json. Do not edit.

pub const rev_iv_set_label: String = "Rev IV RPA set (glm-ocr-audited)"

pub fn rev_iv_label(code: String) -> Result(String, Nil) {
  case code {
    "101" -> Ok("Appraisal of Soil Resources")
    "102" -> Ok("Soil, Plant, Water, Nutrient Relationships")
    "103" -> Ok("Management of Saline and Sodic Soils and Salinity")
    "104" -> Ok("Alternative Uses of Land")
    "105" -> Ok("Conservation and Efficient Use of Water")
    "106" -> Ok("Efficient Drainage and Irrigation Systems and Facilities")
    "107" -> Ok("Watershed Protection and Management")
    "108" ->
      Ok("Economic and Legal Problems in Management of Water and Watersheds")
    "109" -> Ok("Adaptation to Weather and Weather Modification")
    "110" -> Ok("Appraisal of Forest and Range Resources")
    "111" ->
      Ok("Biology, Culture and Management of Forests and Timber-Related Crops")
    "112" -> Ok("Improvement of Range Resources")
    "113" -> Ok("Remote Sensing")
    "114" -> Ok("Research on Management of Research")
    "201" -> Ok("Control of Insects Affecting Forests")
    "202" ->
      Ok("Control of Diseases, Parasites and Nematodes Affecting Forests")
    "203" -> Ok("Prevention and Control of Forest and Range Fires")
    "204" ->
      Ok(
        "Control of Insects, Mites, Slugs and Snails on Fruit and Vegetable Crops",
      )
    "205" ->
      Ok("Control of Diseases and Nematodes of Fruit and Vegetable Crops")
    "206" ->
      Ok("Control of Weeds and Other Hazards to Fruit and Vegetable Crops")
    "207" ->
      Ok(
        "Control of Insects, Mites, Snails and Slugs Affecting Field Crops and Range",
      )
    "208" -> Ok("Control of Diseases and Nematodes of Field Crops and Range")
    "209" -> Ok("Control of Weeds and Other Hazards of Field Crops and Range")
    "210" ->
      Ok(
        "Control of Insects and External Parasites Affecting Livestock, Poultry and Other Animals",
      )
    "211" -> Ok("Control of Diseases of Livestock, Poultry and Other Animals")
    "212" ->
      Ok(
        "Control of Internal Parasites of Livestock, Poultry and Other Animals",
      )
    "213" ->
      Ok(
        "Protect Livestock, Poultry and Other Animals from Toxic Chemicals, Poisonous Plants and Other Hazards",
      )
    "214" ->
      Ok(
        "Protection of Plants, Animals and Man from Harmful Effects of Pollution",
      )
    "301" -> Ok("Genetics and Breeding of Forest Trees")
    "302" -> Ok("New and Improved Forest Engineering Systems")
    "303" -> Ok("Economics of Timber Production")
    "304" ->
      Ok("Improvement of Biological Efficiency of Fruit and Vegetable Crops")
    "305" -> Ok("Mechanization of Fruit and Vegetable Crop Production")
    "306" -> Ok("Production Management Systems for Fruits and Vegetables")
    "307" -> Ok("Improvement of Biological Efficiency of Field Crops")
    "308" -> Ok("Mechanization of Production of Field Crops")
    "309" -> Ok("Production Management Systems for Field Crops")
    "310" ->
      Ok("Reproductive Performance of Livestock, Poultry and Other Animals")
    "311" ->
      Ok(
        "Improvement of Biological Efficiency in Production of Livestock, Poultry and Other Animals",
      )
    "312" ->
      Ok(
        "Environmental Stress in Production of Livestock, Poultry and Other Animals",
      )
    "313" ->
      Ok(
        "Production Management Systems for Livestock, Poultry and Other Animals",
      )
    "314" -> Ok("Bees and Other Pollinating Insects")
    "315" ->
      Ok(
        "Improvement of Structures, Facilities and General Purpose Farm Supplies and Equipment",
      )
    "316" -> Ok("Farm Business Management")
    "317" ->
      Ok(
        "Mechanization and Structures Used in Production of Livestock, Poultry and Other Animals",
      )
    "318" -> Ok("Non-Commodity-Oriented Biological Technology and Biometry")
    "401" -> Ok("New and Improved Forest Products")
    "402" ->
      Ok("Production of Fruit and Vegetable Crops with Improved Acceptability")
    "403" -> Ok("New and Improved Fruit and Vegetable Products and Byproducts")
    "404" ->
      Ok("Quality Maintenance in Storing and Marketing Fruits and Vegetables")
    "405" -> Ok("Production of Field Crops with Improved Acceptability")
    "406" -> Ok("New and Improved Food Products from Field Crops")
    "407" ->
      Ok(
        "New and Improved Feed, Textile and Industrial Products from Field Crops",
      )
    "408" -> Ok("Quality Maintenance in Storing and Marketing Field Crops")
    "409" -> Ok("Production of Animal Products with Improved Acceptability")
    "410" ->
      Ok("New and Improved Meat, Milk, Eggs and Other Animal Food Products")
    "411" -> Ok("New and Improved Non-Food Animal Products")
    "412" -> Ok("Quality Maintenance in Marketing Animal Products")
    "501" -> Ok("Improvement of Grades and Standards--Crop and Animal Products")
    "502" ->
      Ok(
        "Development of Markets and Efficient Marketing of Timber and Related Products",
      )
    "503" ->
      Ok("Efficiency in Marketing Agricultural Products and Production Inputs")
    "506" -> Ok("Supply, Demand and Price Analysis--Crop and Animal Products")
    "507" -> Ok("Competitive Interrelationships in Agriculture")
    "508" -> Ok("Development of Domestic Markets for Farm Products")
    "509" -> Ok("Performance of Marketing Systems")
    "510" -> Ok("Group Action and Market Power")
    "511" -> Ok("Improvement in Agricultural Statistics")
    "512" -> Ok("Improvement of Grades and Standards of Forest Products")
    "513" -> Ok("Supply, Demand and Price Analysis--Forest Products")
    "601" -> Ok("Foreign Market Development")
    "602" -> Ok("Evaluation of Foreign Food Aid Programs")
    "603" -> Ok("Technical Assistance to Developing Countries")
    "604" -> Ok("Product Development and Marketing for Foreign Markets")
    "701" ->
      Ok(
        "Insure Food Products Free of Toxic Contaminants Including Residues from Agricultural and Other Sources",
      )
    "702" ->
      Ok(
        "Protect Food and Feed Supplies from Harmful Microorganisms and Naturally Occurring Toxins",
      )
    "703" -> Ok("Food Choices, Habits and Consumption")
    "704" -> Ok("Home and Commercial Food Service")
    "705" -> Ok("Selection and Care of Clothing and Household Textiles")
    "706" -> Ok("Control of Insect Pests of Man and His Belongings")
    "707" -> Ok("Prevent Transmission of Animal Diseases and Parasites to Man")
    "708" -> Ok("Human Nutrition")
    "709" -> Ok("Reduction of Hazards to Health and Safety")
    "801" -> Ok("Housing")
    "802" ->
      Ok(
        "Individual and Family Decision Making and Resource Use and Family Functioning",
      )
    "803" -> Ok("Causes of Poverty Among Rural People")
    "804" -> Ok("Improvement of Economic Potential of Rural People")
    "805" -> Ok("Communication and Education Processes")
    "806" -> Ok("Individual and Family Adjustment to Change")
    "807" -> Ok("Structural Changes in Agriculture")
    "808" -> Ok("Government Programs to Balance Farm Output and Market Demand")
    "901" ->
      Ok("Alleviation of Soil, Water and Air Pollution and Disposal of Wastes")
    "902" -> Ok("Outdoor Recreation")
    "903" ->
      Ok(
        "Multiple Use Potential of Forest Land and Evaluation of Forestry Programs",
      )
    "904" ->
      Ok("Fish and Other Aquatic Life, Fur-Bearing Animals and Other Wildlife")
    "905" -> Ok("Trees to Enhance Rural and Urban Environment")
    "906" -> Ok("Culture and Protection of Ornamentals and Turf")
    "907" -> Ok("Improved Income Opportunities in Rural Communities")
    "908" -> Ok("Improvement of Rural Community Institutions and Services")
    _ -> Error(Nil)
  }
}

pub const fy94_table_set_label: String = "FY94 table RPA set (annual-table)"

pub fn fy94_table_label(code: String) -> Result(String, Nil) {
  case code {
    "101" -> Ok("APPRAIS OF SOIL RES")
    "102" -> Ok("SOIL PLNT WTR NUTRI")
    "103" -> Ok("MGMT OF SALINE SOIL")
    "104" -> Ok("ALTERN USE OF LAND")
    "105" -> Ok("CONSERV USE OF WATE")
    "106" -> Ok("DRAIN AND IRRIGATIO")
    "107" -> Ok("WATERSHED PROT & MG")
    "108" -> Ok("ECON LEG PROB OF WA")
    "109" -> Ok("WEATHER ADAPT & MOD")
    "110" -> Ok("APPRAIS FORST & RAN")
    "111" -> Ok("BIOL CULT MGMT FORS")
    "112" -> Ok("IMPROV RANGE RESOR")
    "113" -> Ok("REMOTE SENSING")
    "114" -> Ok("RSCH ON MGMT OF RSC")
    "201" -> Ok("CNTRL FORST INSECTS")
    "202" -> Ok("CONTROL FOREST DIS")
    "203" -> Ok("FOREST FIRE PROTECT")
    "204" -> Ok("CNTR PESTS FRT & VE")
    "205" -> Ok("CNTR DISE FRT & VEG")
    "206" -> Ok("CNTR WEEDS FRT & VE")
    "207" -> Ok("CNTR PESTS FLD CROP")
    "208" -> Ok("CNTR DIS FIELD CROP")
    "209" -> Ok("CNTR WEEDS FLD CROP")
    "210" -> Ok("CONTR PESTS ANIMALS")
    "211" -> Ok("CONTR DIS ANIMALS")
    "212" -> Ok("CNTR INTER PARASITE")
    "213" -> Ok("PROT ANMLS FROM TOX")
    "214" -> Ok("PROTECT FROM POLLUT")
    "301" -> Ok("GENET BREED FORST T")
    "302" -> Ok("IMP FOREST ENG SYS")
    "303" -> Ok("ECON TIMBER PRODUCT")
    "304" -> Ok("IMP BIO EFF FRT & V")
    "305" -> Ok("MECH PROD FRT & VEG")
    "306" -> Ok("PROD MGMT SYS F & V")
    "307" -> Ok("IMP BIO EFF FLD CRP")
    "308" -> Ok("MECH PROD FIELD CRO")
    "309" -> Ok("PROD MGMT SYS FLD C")
    "310" -> Ok("ANIMAL REPRODUCTION")
    "311" -> Ok("IMP BIO EFF ANML PR")
    "312" -> Ok("ENV STRESS IN ANML")
    "313" -> Ok("PROD MGMT SYS ANML")
    "314" -> Ok("BEES OTH POLLNTNG I")
    "315" -> Ok("IMP STRUC FARM SUPP")
    "316" -> Ok("FARM BUSINESS MGMT")
    "317" -> Ok("MECH/STRUCTS ANML P")
    "318" -> Ok("NON-COM BIO TECH/BI")
    "401" -> Ok("NEW IMP FOREST PROD")
    "402" -> Ok("PROD F & V IMP ACCE")
    "403" -> Ok("NEW & IMP F&V PROD")
    "404" -> Ok("MKT QUAL FRTS & VEG")
    "405" -> Ok("PROD FLD CROP IMP A")
    "406" -> Ok("NEW IMP FOOD FLD CR")
    "407" -> Ok("NEW IMP NON-FOOD FC")
    "408" -> Ok("MKT QUAL FIELD CROP")
    "409" -> Ok("PROD ANML PR IMP AC")
    "410" -> Ok("IMP MEAT MILK EGG P")
    "411" -> Ok("IMP NON-FOOD ANML P")
    "412" -> Ok("MKT QUAL ANIMAL PRO")
    "501" -> Ok("IMP GRADES & STANDS")
    "502" -> Ok("MKTG TIMBER PRODUCT")
    "503" -> Ok("MKTG EFF AGRI PRODS")
    "506" -> Ok("SPLY DEMAND AND PRI")
    "507" -> Ok("COMP REL IN AGRIC")
    "508" -> Ok("DOMESTIC MKT DEVELP")
    "509" -> Ok("PERFORMANCE MKTG SY")
    "510" -> Ok("GROUP ACT MKT POWER")
    "511" -> Ok("IMP AGRIC STATISTIC")
    "512" -> Ok("IMP GRADES FRST PRO")
    "513" -> Ok("PRICE ANAL FRST PRO")
    "601" -> Ok("FGN MKT DEVELP")
    "602" -> Ok("EVAL FGN FOOD AID P")
    "603" -> Ok("TECH AID DEV CRTY")
    "604" -> Ok("PRD DVLPMT/MKTG FRG")
    "701" -> Ok("TOX RES IN FOOD")
    "702" -> Ok("FOOD PROT FROM TOX")
    "703" -> Ok("FOOD CONSUMP HABITS")
    "704" -> Ok("HOME COMM FOOD SERV")
    "705" -> Ok("SEL CARE CLOTH & TE")
    "706" -> Ok("CONTR INSECTS AFF M")
    "707" -> Ok("TRANS  ANIML MAN DI")
    "708" -> Ok("HUMAN NUTRITION")
    "709" -> Ok("REDUCE HAZ HLTH & S")
    "801" -> Ok("RURAL HOUSING")
    "802" -> Ok("INDIV & FAM DEC MAK")
    "803" -> Ok("RURAL POVERTY")
    "804" -> Ok("ECON POTENT RURL PE")
    "805" -> Ok("COMMUNICAT RURAL PE")
    "806" -> Ok("ADJUSTMENT TO CHANG")
    "807" -> Ok("AGRIC ECONOMIC CHAN")
    "808" -> Ok("GOV'T PROGRAMS")
    "901" -> Ok("ALLEV POLLUTION")
    "902" -> Ok("OUTDOOR RECREATION")
    "903" -> Ok("MULTI-USE-FOREST PO")
    "904" -> Ok("WLDLFE AND FISH ECO")
    "905" -> Ok("TREES BEAUTIFICATIO")
    "906" -> Ok("ORNAMENT & TURF DEV")
    "907" -> Ok("RURAL INCOME IMP")
    "908" -> Ok("RURAL INSTITUT IMP")
    _ -> Error(Nil)
  }
}
