// packages/cris-formatb/scripts/gen-vocab.mjs
// Generates src/vocab_rpa.gleam from the two warrant datasets. Authored JSON is
// the source of truth; this module is derived and never hand-edited.
//
// Build script, not a test file: it may spawn `gleam format` as a subprocess
// (test files may not — see test/regression/no-subprocess.test.ts).
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, "..");
const vocabDir = join(here, "..", "..", "..", "registry", "vocab");
const out = join(pkgDir, "src", "vocab_rpa.gleam");

const SETS = [
  { fn: "rev_iv_label", label: "rev_iv_set_label", set: "Rev IV RPA set", file: "rpa-rev-iv-1982.json" },
  { fn: "fy94_table_label", label: "fy94_table_set_label", set: "FY94 table RPA set", file: "rpa-fy94-table.json" },
];

function gleamString(s) {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

// Pure: reads the two warrant datasets and returns the raw (unformatted)
// Gleam module source. No I/O other than reading the JSON inputs.
export function render() {
  let body = "//// GENERATED by scripts/gen-vocab.mjs from registry/vocab/*.json. Do not edit.\n\n";
  for (const s of SETS) {
    const data = JSON.parse(readFileSync(join(vocabDir, s.file), "utf8"));
    body += `pub const ${s.label}: String = ${gleamString(`${s.set} (${data.rows[0].method})`)}\n\n`;
    body += `pub fn ${s.fn}(code: String) -> Result(String, Nil) {\n  case code {\n`;
    for (const r of data.rows) {
      body += `    ${gleamString(r.code)} -> Ok(${gleamString(r.label)})\n`;
    }
    body += "    _ -> Error(Nil)\n  }\n}\n\n";
  }
  return body;
}

function formatFile(path) {
  execFileSync("gleam", ["format", path], { cwd: pkgDir });
}

function check() {
  const tmpDir = mkdtempSync(join(tmpdir(), "vocab-rpa-check-"));
  const tmpFile = join(tmpDir, "vocab_rpa.gleam");
  let inSync;
  try {
    writeFileSync(tmpFile, render());
    formatFile(tmpFile);
    const formatted = readFileSync(tmpFile, "utf8");
    const committed = readFileSync(out, "utf8");
    inSync = formatted === committed;
  } finally {
    // Always clean up the temp file/dir, even if `render`/`formatFile` throws.
    rmSync(tmpDir, { recursive: true, force: true });
  }
  if (!inSync) {
    console.error("vocab_rpa.gleam is stale — run: node scripts/gen-vocab.mjs");
    process.exit(1);
  }
  process.exit(0);
}

function generate() {
  writeFileSync(out, render());
  formatFile(out);
  console.log(`wrote ${out}`);
}

if (process.argv.includes("--check")) {
  check();
} else {
  generate();
}
