// packages/cris-formatb/scripts/gen-vocab.mjs
// Generates src/vocab_rpa.gleam from the two warrant datasets. Authored JSON is
// the source of truth; this module is derived and never hand-edited.
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const vocabDir = join(here, "..", "..", "..", "registry", "vocab");
const out = join(here, "..", "src", "vocab_rpa.gleam");

const SETS = [
  { fn: "rev_iv_label", label: "rev_iv_set_label", set: "Rev IV RPA set", file: "rpa-rev-iv-1982.json" },
  { fn: "fy94_table_label", label: "fy94_table_set_label", set: "FY94 table RPA set", file: "rpa-fy94-table.json" },
];

function gleamString(s) {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

let body = "//// GENERATED by scripts/gen-vocab.mjs from registry/vocab/*.json. Do not edit.\n\n";
for (const s of SETS) {
  const data = JSON.parse(readFileSync(join(vocabDir, s.file), "utf8"));
  body += `pub const ${s.label}: String = ${gleamString(`${s.set} (${data.rows[0].method})`)}\n\n`;
  body += `pub fn ${s.fn}(code: String) -> Result(String, Nil) {\n  case code {\n`;
  for (const r of data.rows) {
    body += `    ${gleamString(r.code)} -> Ok(${gleamString(r.label)})\n`;
  }
  body += "    _ -> Error(Nil)\n  }\n}\n\n";
}
writeFileSync(out, body);
execFileSync("gleam", ["format", out], { cwd: join(here, "..") });
console.log(`wrote ${out}`);
